apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: quick
spec:
  rules:
    - host: api.example.com
      http:
        paths:
          - path: /v1
            pathType: Prefix
            backend:
              service:
                name: api-v1
                port:
                  number: 8080
