apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: backend
  name: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - image: nginx:1.21
        name: nginx
        resources:
          requests:
            cpu: 100m
            memory: 64Mi
        volumeMounts:
          - mountPath: /etc/db
            name: db-cfg-mnt
        readinessProbe:
          httpGet:
            port: 80
            path: /
      volumes:
        - name: db-cfg-mnt
          configMap:
            name: db-config

