apiVersion: v1
kind: Pod
metadata:
  labels:
    run: data-pod
  name: data-pod
spec:
  volumes:
    - name: data-mnt
      persistentVolumeClaim:
        claimName: data-pvc
  containers:
  - image: nginx:1.21
    name: data-pod
    volumeMounts:
      - mountPath: /usr/share/nginx/html
        name: data-mnt
