apiVersion: v1
kind: Pod
metadata:
  name: limited
  labels:
    block: '4'
    task: quick
spec:
  containers:
    - name: limited
      image: nginx:1.21
      resources:
        requests:
          memory: 64Mi
          cpu: 250m
        limits:
          memory: 128Mi
          cpu: 500m
