kind: Pod
apiVersion: v1
metadata:
  name: init-demo
  labels:
    app: demo
spec:
  containers:
    - name: init-demo
      image: nginx:1.21
      ports:
        - containerPort: 80
      volumeMounts:
        - name: shared-data
          mountPath: /usr/share/nginx/html
  initContainers:
    - name: busybox
      image: busybox
      command: ['sh', '-c', 'echo initialized > /work/status']
      volumeMounts:
        - name: shared-data
          mountPath: /work
  volumes:
    - name: shared-data
      emptyDir: {}
