apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: cache
  name: cache
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cache
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: cache
    spec:
      containers:
      - image: redis:7
        name: redis
        resources: 
          limits:
            cpu: 1
            memory: 512Mi
          requests:
            cpu: 1
            memory: 256Mi
status: {}
