apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: web
  name: web
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - image: nginx:1.21
        name: nginx
        resources:
          limits:
            cpu: 2
            memory: 256Mi
          requests:
            cpu: 1
            memory: 256Mi
        livenessProbe:
          initialDelaySeconds: 5
          httpGet:
            path: "/"
            port: 80
      - image: busybox
        name: logger
        command: ['sh', '-c', 'while true; do echo "$(date) already?"; sleep 2; done;']
