apiVersion: v1
kind: Pod
metadata:
  labels:
    run: multi
  name: multi
spec:
  containers:
    - image: nginx:1.21
      name: multi
      ports:
        - containerPort: 80
    - image: busybox
      name: log
      command: ['sh', '-c', 'while true; do [ $((RANDOM % 2)) -eq 0 ] && echo heads || echo tails; sleep 1; done;']
  dnsPolicy: ClusterFirst
  restartPolicy: Always
