apiVersion: v1
kind: Pod
metadata:
  name: mem-scratch
spec:
  volumes:
    - name: cache-mnt
      emptyDir: {
        medium: Memory
      }
  containers:
    - name: mem-scratch
      image: busybox
      command:
        - sh
        - -c 
        - sleep 3600
      volumeMounts:
        - name: cache-mnt 
          mountPath: /cache

