apiVersion: v1
kind: ConfigMap
metadata:
  name: app-cfg
data:
  ENV: prod
  LOG_LEVEL: info

---

apiVersion: v1
kind: Secret
metadata:
  name: app-secret
type: Opaque
stringData:
  API_KEY: abc123
data:
  API_KEY_ENC: YWJjMTIz

---

apiversion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    containers:
      - image: nginx:1.21
        name: nginx
        ports:
          - containerPort: 80
        readinessProbe:
          httpGet:
            path: /
            port: 80
        envFrom:
          - configMapRef:
              name: app-cfg
        env:
          - name: API_KEY
            valueFrom:
              configMapKeyRef:
                name: app-secret
                key: APP_API_KEY

---

apiVersion: v1
kind: Service
metadata:
  name: app-svc
spec:
  selector:
    app: app
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
