apiVersion: v1
kind: ConfigMap
metadata:
  name: cfg
data:
  env: prod
  log_level: warn
  tz: BST

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: dep-env-from
spec:
  replicas: 2
  selector:
    matchLabels:
      env-from: configMapRef
  template:
    metadata:
      labels:
        env-from: configMapRef
    spec:
      initContainers:
        - image: busybox
          name: env-from
          restartPolicy: Never
          command: ['sh', '-c', 'env']
          env:
            - name: TIMEZONE
              valueFrom:
                configMapKeyRef:
                  key: tz
                  name: cfg
            - value: "123"
              name: test  
            - value: $(test)456
              name: test-ext
      containers:
        - image: nginx:1.21
          name: a-name
