apiVersion: v1
kind: ConfigMap
metadata:
  name: app-cfg
data:
  ENV: prod
  LOG_LEVEL: warn

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  labels:
    the: app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - image: nginx:1.21
          name: nginx
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: app-cfg

---

apiVersion: v1
kind: Service
metadata:
  name: app-svc
spec:
  selector:
    app: app
  ports:
    - name: the-port
      port: 80
      targetPort: 80
