apiVersion: batch/v1
kind: Job
metadata:
  name: batch
spec:
  parallelism: 1
  completions: 1
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: worker
          image: busybox
          command: ['sh', '-c', 'echo "done"']


