apiVersion: batch/v1
kind: Job
metadata:
  name: batch-job
spec:
  completions: 3
  parallelism: 1
  template:
    spec:
      restartPolicy: Never
      containers:
        - image: busybox
          name: worker
          command: ['sh', '-c', 'echo "donezo"']

