apiVersion: v1
kind: Pod
metadata:
  labels:
    run: stress
  name: stress
spec:
  containers:
    - command:
        - sh 
        - -c 
        - 'i=0; while true; do i=$((i+1)); s="$s$(head -c 1048576 /dev/zero | tr "\0" x)"; echo "${i}MB"; done'
      image: busybox
      name: stress
      resources: 
        requests:
          memory: 32Mi
        limits:
          memory: 64Mi
