apiVersion: v1
kind: Pod
metadata:
  labels:
    run: whoami
  name: whoami
spec:
  containers:
    - command:
        - sleep
        - "3600"
      image: busybox
      name: whoami
      resources:
        requests:
          cpu: 10m
          memory: 64Mi
        limits:
          cpu: 20m
          memory: 128Mi
      env:
        - name: MY_POD_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.podIP
        - name: MY_POD_NAME
          valueFrom: 
            fieldRef:
              fieldPath: metadata.name
        - name: MY_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: MY_LABEL
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['run']
        - name: CPU_REQUEST
          valueFrom:
            resourceFieldRef:
              resource: requests.cpu
        - name: MEM_LIMIT
          valueFrom:
            resourceFieldRef:
              resource: limits.memory
