apiVersion: v1
kind: Pod
metadata:
  name: already-here-boss
  labels:
    useful: "nope"
    preexisting: "yes"
    test: "pass"
spec:
  containers:
    - name: logger
      image: busybox
      command: ['sh', '-c', 'while true; do echo $(date); sleep 2; done;']
