apiVersion: v1
kind: Pod
metadata:
  name: db
  labels:
    app: db
spec:
  containers:
    - image: redis:7
      name: redis
      readinessProbe:
        exec:
          command: ['sh', '-c', 'redis-cli ping']

