apiVersion: v1
kind: Pod
metadata:
  labels:
    run: buffer
  name: buffer
spec:
  containers:
  - command:
    - sleep
    - "3600"
    image: busybox
    name: buffer
    resources:
      requests:
        cpu: 50m
        memory: 32Mi
      limits:
        cpu: 100m
        memory: 64Mi
    volumeMounts:
      - mountPath: /buffer
        name: empty-dir
  volumes:
    - name: empty-dir
      emptyDir: {}
