apiVersion: v1
kind: ConfigMap
metadata:
  name: app-cfg
  labels:
    configuration: app
data:
  ENV: prod
  LOG_LEVEL: warn

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  labels:
    app: app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app  
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - name: app
          image: nginx:1.21
          envFrom:
            - configMapRef:
                name: app-cfg
          env:
            - name: LOG_LEVEL
              valueFrom:
                configMapKeyRef:
                  name: app-cfg
                  key: LOG_LEVEL
          livenessProbe: 
            initialDelaySeconds: 5
            httpGet:
              path: '/'
              port: 80
                       
---
apiVersion: v1
kind: Service
metadata:
  name: app-svc
spec:
  type: ClusterIP
  selector:
    app: app
  ports:
    - port: 80
      targetPort: 80
