apiVersion: batch/v1
kind: CronJob
metadata:
  name: log-sweep
spec:
  schedule: "5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          containers:
            - image: busybox
              name: sweeper
              command: ['sh', '-c', 'echo sweep']
