apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-cfg
data:
  index.html: |
    <html>
      <h1 style="background: black; color: alpine-blue">Hello There!</h1>
    </html>

---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: frontend
  name: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  strategy: {}
  template:
    metadata:
      labels:
        app: frontend
    spec:
      volumes:
        - name: fe-cfg-mnt
          configMap:
            name: frontend-cfg
      containers:
      - image: nginx:1.21
        name: nginx
        ports:
          - containerPort: 80 
        readinessProbe:
          httpGet:
            path: /
            port: 80
        volumeMounts:
          - mountPath: /usr/share/nginx/html
            name: fe-cfg-mnt

---

apiVersion: v1
kind: Service
metadata:
  name: frontend-svc
spec:
  type: ClusterIP
  selector:
    app: frontend
  ports:
    - port: 80
      targetPort: 80
