apiVersion: v1
kind: Pod
metadata:
  name: initialization
  labels:
    week: "2"
    day: "2"
    fluency: "4"
spec:
  initContainers:
    - name: initializer
      image: busybox
      command: ['sh', '-c', 'echo "That there is ready"']
  containers:
    - name: the-app
      image: nginx:1.21
      ports:
        - containerPort: 80
