apiVersion: v1
kind: Pod
metadata:
  name: multi-container-drifting
  labels:
    week: "2"
    day: "2"
    fluency: "3"
spec:
  containers:
    - name: main-app
      image: nginx:1.21
      ports:
        - containerPort: 80
    - name: logger
      image: busybox
      command: ['sh', '-c', 'while true; do echo "LOGGING"; sleep 3; done']
