apiVersion: v1
kind: Pod
metadata:
  labels:
    run: manual-pod
  name: manual-pod
spec:
  volumes:
    - name: tmp-mnt
      persistentVolumeClaim:
        claimName: manual-pvc
  containers:
    - command: ['sh', '-c',' df -h /pvc; sleep 60;']
      image: busybox
      name: manual-pod
      volumeMounts:
        - mountPath: /pvc
          name: tmp-mnt 
