apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: web-sts
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-sts
  serviceName: web-headless
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: [ReadWriteOnce]
        resources:
          requests:
            storage: 1Gi
  template:
    metadata:
      labels:
        app: nginx-sts
    spec:
      containers:
        - image: nginx:1.21
          name: nginx
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: /usr/share/nginx/html
              name: data
